#
# Spice Chat Filter, made by SpiceDev.
# https://www.spigotmc.org/resources/spice-chat-filter-scf.99400/
# https://github.com/Spice-Development/SpiceChatFilter
#

EnableSCF: true
AntiSpamTimer: 2
