name: SpiceCF
version: '1.5'
main: xyz.spicedev.spicecf.SpiceCF
authors: [ SpiceDev ]
description: SpiceDev basic chat filter
website: SpiceDev.xyz
commands:
  scf:
    description: Main command for SCF
    usage: /<command>
    permission-message: You need the permission scf.staff to use this command
  scf help:
    description: Displays the available commands
    usage: /<command>
  scf reload:
    description: Reloads SCF
    usage: /<command>
  scf settimer:
    description: Sets the antispam timer in seconds
    usage: /<command>
    permission-message: You need the permission scf.staff to use this command
  scf setenable:
    description: Enables or disables SCF
    usage: /<command>
    permission-message: You need the permission scf.staff to use this command
permissions:
  scf.*:
    description: Wildcard permission for SCF
    children:
      scf.staff: true
      scf.bypass.links: true
      scf.bypass.spam: true
      scf.bypass.filter: true
  scf.staff:
    description: Generic staff permission for SCF, access to all features
  scf.bypass.links:
    description: Link filter bypass
  scf.bypass.spam:
    description: Spam filter bypass
  scf.bypass.filter:
    description: General filter bypass